### PR TITLE
Delta argument sorting

### PR DESCRIPTION
**Pull request by jenskutilek**
According to [the spec](https://learn.microsoft.com/de-de/typography/opentype/spec/tt_instructions#managing-exceptions), the argument list for delta instructions must be sorted by ppm:

> NOTE: Always observe that DELTA instructions expect the argument list to be sorted according to ppem. The lowest ppem should be deepest on the stack, and the highest ppem should be topmost on the stack.

This PR sorts the arguments accordingly.

### CODE REVIEW

**Comment by madig** [comment]
Can you please rebase your PR on the latest master? Can't seem to do that from here...

**Comment by jenskutilek** [comment]
I hope I did it correctly. Rebasing is one of the git mysteries to me ;)

**Comment by madig** [comment]
Oops, erm. Now this PR is re-pulling my commits to master 🤔 

Try again with `git rebase -i origin/master` and delete the lines that "pick" the commits already in master, then force-push.

**Comment by madig** [comment]
(I just updated master, please pull before rebasing)

**Comment by jenskutilek** [comment]
Ok, thanks! I think it worked. (I should never trust a git gui to do the right thing ;))

**Comment by madig** [comment]
Wait, weren't there 4 commits? Or did you squash?

**Comment by madig** [comment]
Also, could you please add a small test?

**Comment by jenskutilek** [comment]
The other 2 commits were unrelated to this and somehow sneaked in with the failed rebase attempt. I will add a test, but probably it will take me a week to find time to work on it.

**Comment by jenskutilek** [comment]
Sorry it took such a long time. I added a test for the delta argument sorting.

**Pull request merged**
